### ISSUE TITLE
TrustFlex Configurator Provisioning Prototype Sample do not provide relevant information on keys

### ISSUE THREAD

**Issue by ronnytittoto** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#1]
Issue Type: <b>Bug Report</b>
#### tpds-core: 2.0.2

When Provisioning Prototype samples I can chose to use my own keys (1) or generate them via the tool (2).
In case I chose option (1) I don't know if the first to be uploaded is root CA or intermediate signer key.
If I chose (2) I am not told where the keys are then stored.

**Comment by KalyanCManukonda** [comment]
We are pleased to inform you that several of the previously reported issues have been addressed in the latest version of our packages and extensions. We kindly request you to update to the latest version and share any observations you may have.

Thank you for your continued use of Microchip tools and for providing valuable feedback.
