### ISSUE TITLE
ATECC608 TFLXTLS assymetric authentication use case - wrong video under learn button

### ISSUE THREAD

**Issue by bugabuga64** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#11]
Issue Type: <b>Bug Report</b>
#### tpds-voila-template: 2.2.3

Use this video : https://teams.microsoft.com/l/message/19:meeting_OGYwY2ZiNDgtOGJmNS00NzZkLThjY2QtMzI2MmYwZDU3M2Vl@thread.v2/1729266293235?context=%7B%22contextType%22%3A%22chat%22%7D

**Comment by KalyanCManukonda** [comment]
Hi, Thank you for your feedback on the use case learning videos. In instances where specific use case videos are not available, we have opted to provide a default product overview video. We will review these internally again and make updates as deemed appropriate.
