### ISSUE TITLE
TA010 TFLXWPC WPC use case - wrong video under learn button  

### ISSUE THREAD

**Issue by bugabuga64** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#13]
Issue Type: <b>Bug Report</b>
#### tpds-voila-template: 2.2.3

https://www.youtube.com/watch?v=oCOmRSzM0K0

**Comment by KalyanCManukonda** [comment]
Hi, Thank you for your feedback on the use case learning videos. In instances where specific use case videos are not available, we have opted to provide a default product overview video. We will review these internally again and make updates as deemed appropriate.
