### ISSUE TITLE
'Provision Prototype Samples' option in Configurator for TrustFLEX cannot connect to ATECC608B in DM320118

### ISSUE THREAD

**Issue by csukang-BR** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#2]
Issue Type: <b>Bug Report</b>
#### tpds-core: 2.0.7

Configuring 'AWS IoT Authentication' and 'Firmware Validation' Usecases using ATECC608B TrustFLEX in Crypto Eval Kit (ie DM320118).
It works when I selected 'Generate Provisioning Package' option in Configurator of Trust Platform Design Suite.
But, it does not work when 'Provision Prototype Samples' option is used.
It always displays a small pop-up with 'Can't connect to device'.
Tried with a couple of Crypto Eval Kit (DM320118) to eliminate that it is not a hardware issue
[ATECC608B-MAHAA-T_1110160845_Proto.zip](https://github.com/Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker/files/7523993/ATECC608B-MAHAA-T_1110160845_Proto.zip)
.

**Comment by KalyanCManukonda** [comment]
We are pleased to inform you that several of the previously reported issues have been addressed in the latest version of our packages and extensions. We kindly request you to update to the latest version and share any observations you may have.

Thank you for your continued use of Microchip tools and for providing valuable feedback.
