### ISSUE TITLE
TPDS v2.3.4 TFLXTLS-Configurator failure

### ISSUE THREAD

**Issue by ReHardy** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#3]
Issue Type: <b>Bug Report</b>
#### tpds-voila-template: 2.2.3

Trying to generate a provisioning package (customized slot 10 + 12 incl. Custom Root Signer CA information with dummy data) always ends up with the failure message 'Failed: invalid EC key'.

Screenshots attached.

[Github_TPDS_v2.3.4_TFLXTLS_Configurator_failure_20221128.docx](https://github.com/Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker/files/10102675/Github_TPDS_v2.3.4_TFLXTLS_Configurator_failure_20221128.docx)

**Comment by KalyanCManukonda** [comment]
Hi [ReHardy](https://github.com/ReHardy), thank you for reporting the observation. 

"Failed: invalid EC key" will be reported when an invalid ECC public key is uploaded for Custom Root Signer CA information. When a valid ECC public key is uploaded, this should work as expected.
