### ISSUE TITLE
TrustMANAGER use case contains the wrong video tutorial

### ISSUE THREAD

**Issue by bugabuga64** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#8]
Issue Type: <b>Bug Report</b>
#### tpds-voila-template: 2.2.3

![image](https://github.com/user-attachments/assets/5116ec2b-123a-4707-96cc-3572347ecf59)

Can you load this tuto instead ? https://www.youtube.com/watch?v=7_13wIr6eRU

**Comment by KalyanCManukonda** [comment]
Thank you for your valuable feedback on the Usecase learning videos. We are pleased to inform you that the latest Chiptorial video on this usecase is now available at the following link: https://www.youtube.com/watch?v=7_13wIr6eRU. This video will be incorporated into the next update of the usecase.
