### ISSUE TITLE
wrong video tuto on symmetric key with diversified key on ECC204 

### ISSUE THREAD

**Issue by bugabuga64** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#9]
Issue Type: <b>Bug Report</b>
#### tpds-voila-template: 2.2.3

![image](https://github.com/user-attachments/assets/e9f34550-7b7b-4aa9-8147-7c269da43a3e)

please use this https://www.youtube.com/watch?v=mBQlsTJjhbw&t=19s

**Comment by KalyanCManukonda** [comment]
Hi, Thank you for your feedback on the use case learning videos. In instances where specific use case videos are not available, we have opted to provide a default product overview video. We will review these internally again and make updates as deemed appropriate.
